version: "2.4"

services:
  backend:
    build:
      dockerfile: development.Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 3000
      - 9229
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URL: mongodb://sample-auth-system:sample-auth-system@database:27017/sample-auth-system
      JWT_SECRET: jgwejh25672@&@*
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app/
    command: ["npx", "nodemon", "--inspect=0.0.0.0"]


  fix-mongodb-permissions:
    image: 'alpine:3.10'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - "backend-data:/bitnami"

  database:
    image: "bitnami/mongodb:4.2"
    restart: always
    depends_on:
      - fix-mongodb-permissions
    expose:
      - 27017
    ports:
      - "27018:27017"
    volumes:
      - "backend-data:/bitnami"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=database
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_ROOT_PASSWORD=SDFsdf5tgdfgdff6sd
      - MONGODB_DATABASE=sample-auth-system
      - MONGODB_USERNAME=sample-auth-system
      - MONGODB_PASSWORD=sample-auth-system
      - MONGODB_EXTRA_FLAGS=--noscripting
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s

volumes:
  backend-data:
    driver: local
