version: "2.4"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 3000
    environment:
      NODE_ENV: test
      PORT: 3000
      MONGO_URL: mongodb://sample-auth-system:sample-auth-system@database:27017/sample-auth-system
      JWT_SECRET: jgwejh25672@&@*
    command: sleep 1000

  database:
    image: "bitnami/mongodb:4.2"
    expose:
      - 27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=database
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_ROOT_PASSWORD=SDFsdf5tgdfgdff6sd
      - MONGODB_DATABASE=sample-auth-system
      - MONGODB_USERNAME=sample-auth-system
      - MONGODB_PASSWORD=sample-auth-system
      - MONGODB_EXTRA_FLAGS=--noscripting
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s
